### ISSUE TITLE
Работает, спасибо, ещё один вопрос :)

### ISSUE THREAD

**Issue by sxiii** [gropox/read_sxiii_posts#1]
Можешь подсказать, как на JS с объектами проще всего работать? Например, я хочу забрать из поста только Title или только выплаты. Или тайтл, а через запятую сумму выплат. Я так понимаю, всего одну строчку дописать в исходник.

**Comment by gropox** [comment]
Ну c title просто. ```content.title```, ```total_payout_value```

Я закоммитил с выплатами. Выдает табличку для Markdown синтаксиса

**Comment by sxiii** [comment]
Круто, спасибо. Буду теперь пытаться перевести это всё на баш =)

**Comment by sxiii** [comment]
Работает, но иногда выдает:
`(node:4367) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit`
И ещё почему-то похоже не совсем корректно генерит markdown:
` + " | " + ` это в выводе отображается склейка таблицы так :)

**Comment by gropox** [comment]
Извращеие)))

**Comment by sxiii** [comment]
Не люблю JS =) А ещё больше ноду не люблю... Мне из баша экспортировать куда угодно и преобразовать проще =)

**Comment by gropox** [comment]
Я честно говоря не сильно тестировал. Поправил с варнингом,  у тебя история слишком большая ))) и макдаун тоже пофиксил
